apiVersion: v1
kind: Service
metadata:
  name: {{ include "y-ai-pond.componentName" (list . "redis") }}
  labels:
    {{- include "y-ai-pond.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "y-ai-pond.componentLabels" (list . "redis") | nindent 4 }}
