{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "y-ai-pond.componentName" (list . "sa") }}
  labels:
    {{- include "y-ai-pond.labels" . | nindent 4 }}
{{- end }}
