// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: camera.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Behavior classifies the observed fish group behavior from YOLOv8n inference.
type Behavior int32

const (
	Behavior_BEHAVIOR_UNSPECIFIED Behavior = 0
	Behavior_BEHAVIOR_AGGREGATING Behavior = 1 // Fish gathering together (normal)
	Behavior_BEHAVIOR_SCATTERING  Behavior = 2 // Fish dispersing (alarm/threat)
	Behavior_BEHAVIOR_FEEDING     Behavior = 3 // Fish actively feeding (positive feeding signal)
)

// Enum value maps for Behavior.
var (
	Behavior_name = map[int32]string{
		0: "BEHAVIOR_UNSPECIFIED",
		1: "BEHAVIOR_AGGREGATING",
		2: "BEHAVIOR_SCATTERING",
		3: "BEHAVIOR_FEEDING",
	}
	Behavior_value = map[string]int32{
		"BEHAVIOR_UNSPECIFIED": 0,
		"BEHAVIOR_AGGREGATING": 1,
		"BEHAVIOR_SCATTERING":  2,
		"BEHAVIOR_FEEDING":     3,
	}
)

func (x Behavior) Enum() *Behavior {
	p := new(Behavior)
	*p = x
	return p
}

func (x Behavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Behavior) Descriptor() protoreflect.EnumDescriptor {
	return file_camera_proto_enumTypes[0].Descriptor()
}

func (Behavior) Type() protoreflect.EnumType {
	return &file_camera_proto_enumTypes[0]
}

func (x Behavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Behavior.Descriptor instead.
func (Behavior) EnumDescriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{0}
}

// InferenceResult is the output of the edge YOLOv8n vision pipeline.
// Published via MQTT QoS 0 to avoid bandwidth saturation from ~100 FPS inference.
type InferenceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FishCount     int32     `protobuf:"varint,1,opt,name=fish_count,json=fishCount,proto3" json:"fish_count,omitempty"`                // Number of fish detected in frame
	Sizes         []float32 `protobuf:"fixed32,2,rep,packed,name=sizes,proto3" json:"sizes,omitempty"`                                 // Estimated fish body lengths in mm, one per detected fish
	Behavior      Behavior  `protobuf:"varint,3,opt,name=behavior,proto3,enum=y_ai_pond.camera.v1.Behavior" json:"behavior,omitempty"` // Dominant group behavior classification
	TextureEnergy float32   `protobuf:"fixed32,4,opt,name=texture_energy,json=textureEnergy,proto3" json:"texture_energy,omitempty"`   // Surface water texture energy (0.0–1.0) for feeding intensity estimation
}

func (x *InferenceResult) Reset() {
	*x = InferenceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camera_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InferenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResult) ProtoMessage() {}

func (x *InferenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResult.ProtoReflect.Descriptor instead.
func (*InferenceResult) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{0}
}

func (x *InferenceResult) GetFishCount() int32 {
	if x != nil {
		return x.FishCount
	}
	return 0
}

func (x *InferenceResult) GetSizes() []float32 {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *InferenceResult) GetBehavior() Behavior {
	if x != nil {
		return x.Behavior
	}
	return Behavior_BEHAVIOR_UNSPECIFIED
}

func (x *InferenceResult) GetTextureEnergy() float32 {
	if x != nil {
		return x.TextureEnergy
	}
	return 0
}

var File_camera_proto protoreflect.FileDescriptor

var file_camera_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13,
	0x79, 0x5f, 0x61, 0x69, 0x5f, 0x70, 0x6f, 0x6e, 0x64, 0x2e, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x2e, 0x76, 0x31, 0x22, 0xa8, 0x01, 0x0a, 0x0f, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x73, 0x68, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x69, 0x73,
	0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x08,
	0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x79, 0x5f, 0x61, 0x69, 0x5f, 0x70, 0x6f, 0x6e, 0x64, 0x2e, 0x63, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x08, 0x62,
	0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x65, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x5f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0d, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x2a, 0x6d,
	0x0a, 0x08, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x14, 0x42, 0x45,
	0x48, 0x41, 0x56, 0x49, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x42, 0x45, 0x48, 0x41, 0x56, 0x49, 0x4f, 0x52,
	0x5f, 0x41, 0x47, 0x47, 0x52, 0x45, 0x47, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x17,
	0x0a, 0x13, 0x42, 0x45, 0x48, 0x41, 0x56, 0x49, 0x4f, 0x52, 0x5f, 0x53, 0x43, 0x41, 0x54, 0x54,
	0x45, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x45, 0x48, 0x41, 0x56,
	0x49, 0x4f, 0x52, 0x5f, 0x46, 0x45, 0x45, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x72, 0x72,
	0x6f, 0x72, 0x2f, 0x79, 0x2d, 0x61, 0x69, 0x2d, 0x70, 0x6f, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_camera_proto_rawDescOnce sync.Once
	file_camera_proto_rawDescData = file_camera_proto_rawDesc
)

func file_camera_proto_rawDescGZIP() []byte {
	file_camera_proto_rawDescOnce.Do(func() {
		file_camera_proto_rawDescData = protoimpl.X.CompressGZIP(file_camera_proto_rawDescData)
	})
	return file_camera_proto_rawDescData
}

var file_camera_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_camera_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_camera_proto_goTypes = []interface{}{
	(Behavior)(0),           // 0: y_ai_pond.camera.v1.Behavior
	(*InferenceResult)(nil), // 1: y_ai_pond.camera.v1.InferenceResult
}
var file_camera_proto_depIdxs = []int32{
	0, // 0: y_ai_pond.camera.v1.InferenceResult.behavior:type_name -> y_ai_pond.camera.v1.Behavior
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_camera_proto_init() }
func file_camera_proto_init() {
	if File_camera_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_camera_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InferenceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_camera_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_camera_proto_goTypes,
		DependencyIndexes: file_camera_proto_depIdxs,
		EnumInfos:         file_camera_proto_enumTypes,
		MessageInfos:      file_camera_proto_msgTypes,
	}.Build()
	File_camera_proto = out.File
	file_camera_proto_rawDesc = nil
	file_camera_proto_goTypes = nil
	file_camera_proto_depIdxs = nil
}
