// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: sensor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SensorReading is the unified sensor data message for pond water quality.
// All fields are transmitted as binary Protobuf via MQTT (QoS 0) for
// high-frequency telemetry from ESP32-S3 sensor nodes to the edge controller.
type SensorReading struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId   string  `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`         // Unique sensor node identifier (e.g. "esp32-s3-01")
	Timestamp  int64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                      // Unix timestamp in milliseconds
	Ph         float32 `protobuf:"fixed32,3,opt,name=ph,proto3" json:"ph,omitempty"`                                   // pH value (0–14)
	Do         float32 `protobuf:"fixed32,4,opt,name=do,proto3" json:"do,omitempty"`                                   // Dissolved oxygen in mg/L (0–20)
	Temp       float32 `protobuf:"fixed32,5,opt,name=temp,proto3" json:"temp,omitempty"`                               // Water temperature in °C (0–50)
	Nh3        float32 `protobuf:"fixed32,6,opt,name=nh3,proto3" json:"nh3,omitempty"`                                 // Ammonia nitrogen in mg/L (0–10)
	Turbidity  float32 `protobuf:"fixed32,7,opt,name=turbidity,proto3" json:"turbidity,omitempty"`                     // Turbidity in NTU (0–3000)
	WaterLevel float32 `protobuf:"fixed32,8,opt,name=water_level,json=waterLevel,proto3" json:"water_level,omitempty"` // Water level in cm
}

func (x *SensorReading) Reset() {
	*x = SensorReading{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReading) ProtoMessage() {}

func (x *SensorReading) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReading.ProtoReflect.Descriptor instead.
func (*SensorReading) Descriptor() ([]byte, []int) {
	return file_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *SensorReading) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SensorReading) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SensorReading) GetPh() float32 {
	if x != nil {
		return x.Ph
	}
	return 0
}

func (x *SensorReading) GetDo() float32 {
	if x != nil {
		return x.Do
	}
	return 0
}

func (x *SensorReading) GetTemp() float32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *SensorReading) GetNh3() float32 {
	if x != nil {
		return x.Nh3
	}
	return 0
}

func (x *SensorReading) GetTurbidity() float32 {
	if x != nil {
		return x.Turbidity
	}
	return 0
}

func (x *SensorReading) GetWaterLevel() float32 {
	if x != nil {
		return x.WaterLevel
	}
	return 0
}

var File_sensor_proto protoreflect.FileDescriptor

var file_sensor_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13,
	0x79, 0x5f, 0x61, 0x69, 0x5f, 0x70, 0x6f, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x2e, 0x76, 0x31, 0x22, 0xcf, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x65,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x70, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x70, 0x68,
	0x12, 0x0e, 0x0a, 0x02, 0x64, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x64, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x74, 0x65, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x68, 0x33, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x6e, 0x68, 0x33, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x75, 0x72, 0x62, 0x69, 0x64,
	0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x74, 0x75, 0x72, 0x62, 0x69,
	0x64, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x77, 0x61, 0x74, 0x65, 0x72,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x72, 0x72, 0x6f, 0x72, 0x2f, 0x79, 0x2d, 0x61, 0x69, 0x2d,
	0x70, 0x6f, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sensor_proto_rawDescOnce sync.Once
	file_sensor_proto_rawDescData = file_sensor_proto_rawDesc
)

func file_sensor_proto_rawDescGZIP() []byte {
	file_sensor_proto_rawDescOnce.Do(func() {
		file_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(file_sensor_proto_rawDescData)
	})
	return file_sensor_proto_rawDescData
}

var file_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sensor_proto_goTypes = []interface{}{
	(*SensorReading)(nil), // 0: y_ai_pond.sensor.v1.SensorReading
}
var file_sensor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sensor_proto_init() }
func file_sensor_proto_init() {
	if File_sensor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sensor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorReading); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sensor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sensor_proto_goTypes,
		DependencyIndexes: file_sensor_proto_depIdxs,
		MessageInfos:      file_sensor_proto_msgTypes,
	}.Build()
	File_sensor_proto = out.File
	file_sensor_proto_rawDesc = nil
	file_sensor_proto_goTypes = nil
	file_sensor_proto_depIdxs = nil
}
